mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from accounts.views import *


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^login/',login_view,name='login'),
    url(r'^logout/',logout_view,name='logout'),
    url(r'^register/',register_view,name='register'),
    url(r'^history/',history_view,name='history'),
    url(r'^', include('neoyoutube.urls')),
]

mysite/neoyoutube/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search_query/',views.search_query_view,name='search_query'),
    url(r'^watch/',views.watch_view,name='watch'),
    url(r'^channel/',views.channel_view,name='channel'),
]

mysite/neoyoutube/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

mysite/accounts/forms.py
from django import forms
from django.contrib.auth import (
	authenticate,
	get_user_model,
	login,
	logout,

	)

User = get_user_model()

class UserLoginForm(forms.Form):
	username = forms.CharField(required=True)
	password = forms.CharField(widget=forms.PasswordInput,required=True)


	def clean(self,*agrs,**kwargs):
		username = self.cleaned_data.get("username")
		password = self.cleaned_data.get("password")

		if username and password:
			user = authenticate(username=username,password=password)

			if not user or user == 'AnonymousUser':
				raise forms.ValidationError("Sorry, that login was invalid. Please try again.")
			if not user.check_password(password):
				raise forms.ValidationError("Incorrect password")
			if not user.is_active:
				raise forms.ValidationError("This user is no longer active")
		return super(UserLoginForm,self).clean(*agrs,**kwargs)

class UserRegisterForm(forms.ModelForm):
	email = forms.EmailField(label='Email address')
	email2 = forms.EmailField(label='Confirm Email')
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:

		model = User
		fields = [
			'username',
			'email',
			'email2',
			'password',
		]
	def clean_email2(self):
		email = self.cleaned_data.get('email')
		email2 = self.cleaned_data.get('email2')

		if email != email2:
			raise forms.ValidationError("Emails must match")
		email_qs = User.objects.filter(email=email)
		if email_qs.exists():
			raise forms.ValidationError("This email has already been register")
		return email

mysite/neoyoutube/views.py
from django.http import HttpResponse
from django.shortcuts import render , redirect
from django.conf import settings

# mongo imports
from pymongo import MongoClient
import pymongo
import operator
import math
# neo4j imports
from py2neo import Graph, authenticate, Node, Relationship



client = MongoClient()
mongodb = client.search_engine
videos = mongodb.videos
db = client.videos
collection = db.videos

authenticate("localhost:7474","neo4j","vegeta")
graph = Graph('http://localhost:7474/db/data/')
#
# most_viewed = videos[0]['videoInfo']['id']

def index(request):
	flag = True
	videos_per_page = 20.0
	if not request.user.is_authenticated():
		flag = False
	top_videos = videos.find().sort('videoInfo.statistics.viewCount',pymongo.DESCENDING)
	show_videos = []
	for t in top_videos:
		description = t['videoInfo']['snippet']['localized']['title']
		t['videoInfo']['snippet']['localized']['title'] = description[:50] + "..."
		show_videos.append(dict(t))

	if 'page' not in request.GET.keys():
		page = 1;
	elif int(request.GET['page'])*videos_per_page > len(show_videos):
		page = len(show_videos)/videos_per_page
	elif int(request.GET['page'])*videos_per_page <=0:
		page = 1
	else:
		page = int(request.GET['page'])

	# print top_videos
	return render(request,'neoyoutube/show.html',
	{
	'flag':flag,
	'show_videos':show_videos[int((page-1)*videos_per_page):int(page*videos_per_page)],
	'page': page,
	'page_range':range(1,int(math.ceil(len(show_videos)/videos_per_page)) + 1),
	'num_results':len(show_videos)
	})
	# return HttpResponse("Hello, world. You're at the polls index.")

def watch_view(request):
	flag = True
	if not request.user.is_authenticated():
		flag = False
	if 'id' not in request.GET.keys():
		return redirect('/')

	id = request.GET['id']


	# print id
	data = dict(videos.find_one({'videoInfo.id': id}))
	s_id = id
	s = "match (n1 {id:'" + s_id + "'})-[r]-(n2)  return n2.id,r.weight;"
	curser = graph.run(s).data()
	# print curser
	update_document = videos.find_one({'videoInfo.id' : id})
	viewCount = update_document['videoInfo']['statistics']['viewCount']
	# print viewCount
	videos.update({'videoInfo.id':id}, {"$set": {'videoInfo.statistics.viewCount': int(viewCount) + 1}}, upsert=False)

	d = {}
	for i in curser:
		try:
			d[i['n2.id']] += int(i['r.weight'])
		except:
			d[i['n2.id']] = int(i['r.weight'])

	# print d
	l = list(sorted(d.items(), key=operator.itemgetter(1)))
	for i in xrange(len(l)):
		l[i] = list(l[i])
		# print l[i][1]
	for i in xrange(len(l)):
		for doc in collection.find({"videoInfo.id" : l[i][0]}):
			l[i][1] += int( doc['videoInfo']['statistics']['likeCount']) - int(doc['videoInfo']['statistics']['dislikeCount']) + int((doc['videoInfo']['statistics']['viewCount'])/50)

	l = sorted(l,key=lambda l:l[1], reverse=True)
	# print(len(l))
	recommends = []
	for i in xrange(len(l)):
		v_data = dict(videos.find_one({'videoInfo.id' : l[i][0]}))
		recommends.append(v_data)
	# print recommends
	return render(request,"neoyoutube/watch.html",{'id':id,'data':data,'recommends':recommends , 'flag':flag})

def search_query_view(request):
	videos_per_page = 10.0
	flag = True
	if not request.user.is_authenticated():
		flag = False

	if 'search' not in request.GET.keys():
		return redirect('/')

	query = request.GET['search']
	if len(query) == 0:
		return redirect('/')

	result = videos.aggregate([
			{ "$match": { "$text": { "$search": query } } },
			{ "$sort": { "score": { "$meta": "textScore" } } },
			{ "$project": { "videoInfo.id": 1, "_id":0, "score": { "$meta": "textScore" }} }
	   	])

	video_data = []
	for res in result:
		# print res["videoInfo"]["id"], res["score"]
		data = dict(videos.find_one({'videoInfo.id' : res['videoInfo']['id']}))
		description = data['videoInfo']['snippet']['localized']['description']
		data['videoInfo']['snippet']['localized']['description'] = description[:200] + "...."
		# print data['videoInfo']['snippet']['localized']['description']
		video_data.append(data)


	if 'page' not in request.GET.keys():
		page = 1;
	elif int(request.GET['page'])*videos_per_page > len(video_data):
		page = int(math.ceil(len(video_data)/videos_per_page))
	elif int(request.GET['page'])*videos_per_page <=0:
		page = 1
	else:
		page = int(request.GET['page'])

 	return render(request,"neoyoutube/search.html",
	{
	'video_data' : video_data[int((page-1)*videos_per_page):int(page*videos_per_page)],
	# 'video_data' : video_data,
	'query' : query ,
	'flag' : flag,
	'page': page,
	'page_range':range(1,int(math.ceil(len(video_data)/videos_per_page)) + 1),
	'num_results':len(video_data)
	})

def channel_view(request):

	videos_per_page = 20.0
	flag = True
	if not request.user.is_authenticated():
		flag = False

	if 'channelid' not in request.GET.keys():
		return redirect('/')

	channelid = request.GET['channelid']
	if len(channelid) == 0:
		return redirect('/')

	channel_videos = []
	video_cursor = videos.find({'videoInfo.snippet.channelId' : channelid})
	for data in video_cursor:
		channel_videos.append(dict(data))

	if 'page' not in request.GET.keys():
		page = 1;
	elif int(request.GET['page'])*videos_per_page > len(channel_videosvideo):
		page = int(math.ceil(len(channel_videos)/videos_per_page))
	elif int(request.GET['page'])*videos_per_page <=0:
		page = 1
	else:
		page = int(request.GET['page'])

 	return render(request,"neoyoutube/channel.html",
	{
	'channel_videos' : channel_videos[int((page-1)*videos_per_page):int(page*videos_per_page)],
	'channelid' : channelid ,
	'flag' : flag,
	'page': page,
	'num_results':len(channel_videos)
	})

mysite/templates/neoyoutube/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<!--Import Google Icon Font-->
<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<!--Import materialize.css-->
{% load static %}
<link type="text/css" rel="stylesheet" href="{% static "materialize/css/materialize.min.css" %}"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

</script>
<title>
	Neo Youtube
</title>
</head>
<body>

	{% block content %}
	<h1>Hi</h1>
	{% endblock content %}
	<!--Import jQuery before materialize.js-->
	<script type="text/javascript" src="{% static "jquery/jquery-3.2.1.min.js" %}"></script>
	<script type="text/javascript" src="{% static "materialize/js/materialize.min.js" %}"></script>
    </body>
</body>
</html>

mysite/templates/neoyoutube/channel.html
{% extends "neoyoutube/index.html" %}
{% block content %}
<div class="row">
 {% for data in channel_videos %}
 <div class="col s3">
   <a href="watch/?id={{data.videoInfo.id}}" class="black-text">
     <div class="card z-depth-2 grey lighten-4">
       <div class="card-image" style = "padding-left: 10px; padding-right: 10px; padding-top: 10px">
         <img src="{{ data.videoInfo.snippet.thumbnails.medium.url  }}">
       </div>
       <div class="card-content">
         <p  class="truncate"><b>{{ data.videoInfo.snippet.localized.title }}</b></p>
            <span style = "font-size:14px"> {{ data.videoInfo.snippet.channelTitle}}</span>
            <span style = "position: absolute; right: 20px; bottom: 0px;"><i class="material-icons dp48">visibility</i><b><sup style = "font-size:14px">{{data.videoInfo.statistics.viewCount }}</sup></b></span>
        </div>
      </div>
    </a>
  </div>
{% endfor %}
</div>
{% endblock content %}

mysite/templates/neoyoutube/form.html
{% extends "neoyoutube/base.html" %}





{% block content %}
<div class="center">
<div class="row">
        <div class="col s12 m6">
          <div class="card">
            <div class="card-content white-text">
              <span class="card-title  teal-text text-darken-4 center"><b>Register</b></span>
              <p>
  <div class="row">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s12">
          <input id="id_username" type="text" class="validate" required="">
          <label for="id_username">Username</label>
        </div> teal darken-4
        <div class="input-field col s12">
          <input id="id_email"  name = "email" type="text" class="validate" required="">
          <label for="id_email">Email address:</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="id_email2" name="email2" type="text" class="validate" required="">
          <label for="id_email2">Confirm Email:</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="id_password" name="password" type="password" class="validate" required="">
          <label for="id_password">Password:</label>
        </div>
      </div>

	<input type='submit' class="btn waves-effect waves-light" value='{{title}}' />
    </form>
  </div>
</p>
    </div>
</div>
</div>
<!--   <div class="container">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s6">
          <input placeholder="Placeholder" id="id_username" type="text" class="validate" required="">
          <label for="id_username">Username</label>
        </div>
        <div class="input-field col s6">
          <input id="id_email"  name = "email" type="text" class="validate" required="">
          <label for="id_email">Email address:</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="id_email2" name="email2" type="text" class="validate" required="">
          <label for="id_email2">Confirm Email:</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="id_password" name="password" type="password" class="validate" required="">
          <label for="id_password">Password:</label>
        </div>
      </div>

	<input type='submit' class="btn waves-effect waves-light" value='{{title}}' />
    </form>
  </div>
 -->
{% endblock content %}

mysite/templates/neoyoutube/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<!--Import Google Icon Font-->
<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<!--Import materialize.css-->

<link type="text/css" rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<style>
#searchButton{
  cursor: pointer;
}
</style>

<title>
	Neo Youtube

</title>
</head>
<body>
  <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper white">
        <form method="GET" action="/search_query" id="searchForm">
          <div class="input-field">
            <input id="search" type="search" required name="search">
            <label class="label-icon offset-s2" for="search">
              <i id="searchButton" class="material-icons  grey-text text-darken-5 ">&nbsp;&nbsp;search&nbsp;&nbsp;</i>
            </label>
            <i class="material-icons">close</i>
          </div>
        </form>
      </div>
    </nav>
  </div>
<nav>
  <div class="nav-wrapper teal">
      <a href="/" class="brand-logo"> Youtube Neo</a>
      <ul class="right hide-on-med-and-down">
        {% if not flag %}
        <li>
          <a class="waves-effect waves-light btn blue-grey lighten-5"  href="/login">
            <span class="blue-grey-text text-darken-4">Login</span>
          </a>
        </li>
        <li>
          <a class="waves-effect waves-light btn blue-grey lighten-5"  href="/register">
            <span class="blue-grey-text text-darken-4">
              SignUp
            </span>
          </a>
        </li>
      {% else %}
      <li>
        <a class="waves-effect waves-light btn blue-grey lighten-5"  href="/logout">
          <span class="blue-grey-text text-darken-4">
            Logout
          </span>
        </a>
      </li>
      {% endif %}
      </ul>
    </div>
</nav>
	{% block content %}

	{% endblock content %}
	<!--Import jQuery before materialize.js-->
	<script type="text/javascript" src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'materialize/js/materialize.min.js' %}"></script>
  <script type="text/javascript">
    document.getElementById("searchButton").onclick = function() {
      document.getElementById("searchForm").submit();
    }
  </script>
</body>
</html>

mysite/templates/neoyoutube/login.html
  {% load staticfiles %}
  <!DOCTYPE html>
  <html lang="en">
  <head>
  <meta charset="utf-8"/>
  <!--Import Google Icon Font-->
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!--Import materialize.css-->

  <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}"  media="screen,projection"/>

        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <style>
  #searchButton{
    cursor: pointer;
  }
  </style>

  <title>
  	Neo Youtube

  </title>
  </head>
  <body>
  <nav>
    <div class="nav-wrapper teal">
        <a href="/" class="brand-logo"> Youtube Neo</a>
        <ul class="right hide-on-med-and-down">
          <li>
            <a class="waves-effect waves-light btn blue-grey lighten-5"  href="/register">
              <span class="blue-grey-text text-darken-4">
                SignUp
              </span>
            </a>
          </li>
        </ul>
      </div>
  </nav>
  {% if form.non_field_errors %}
    <ul class='form-errors'>
        {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
        {% endfor %}
    </ul>
{% endif %}
  <!-- <div class="center">
    <div class="container">
        <div class="col s12 m6">
          <div class="card">
            <div class="card-content white-text">
              <span class="card-title  teal-text text-darken-4 center"><b>Login</b></span>
              <p>
                <div class="row">
                  <form method='POST' class="col s12 black-text" action='' enctype='multipart/form-data'>
                    {% csrf_token %}
                  {{ form }}
                  <input type='submit' class='btn waves-effect waves-light' value='{{title}}' />
                  </form>

                </div>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div> -->
    <div class="row" style = "padding-top:20px">
      <div class="col s6 offset-s3">

        <div class="card z-depth-3 grey lighten-4">
          <form method='POST' action='' enctype='multipart/form-data'>
            {% csrf_token %}

          <div class="card-content" style="padding-bottom:0px">
            <span class="card-title center" style="padding-top:0px ;margin-top:0px"><h4 style="margin-top:0px">Login</h4></span>
            <div class="row">
              <div class="input-field col s12">
                <input id="username" name="username" type="text" class="validate" required="">
                <label for="username">Username</label>
              </div>
              <div class="input-field col s12">
                <input id="password" name="password" type="password" class="validate" required="">
                <label for="password">Password</label>
              </div>
            </div>
          </div>
          <div class="card-action" style="padding:0px;margin:5px">
          <div class="row">
            <div class="input-field center" style="margin:20px">
              <input type="submit" value="SignIn" class="btn waves-effect">
            </div>
          </div>
          </div>
        </form>
        </div>
      </div>
    </div>

  	<!--Import jQuery before materialize.js-->
  	<script type="text/javascript" src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
  	<script type="text/javascript" src="{% static 'materialize/js/materialize.min.js' %}"></script>
    <script type="text/javascript">

    </script>
  </body>
  </html>

mysite/templates/neoyoutube/register.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<!--Import Google Icon Font-->
<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<!--Import materialize.css-->

<link type="text/css" rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<style>
#searchButton{
  cursor: pointer;
}
</style>

<title>
  Neo Youtube

</title>
</head>
<body>
<nav>
  <div class="nav-wrapper teal">
      <a href="/" class="brand-logo"> Youtube Neo</a>
      <ul class="right hide-on-med-and-down">
        <li>
          <a class="waves-effect waves-light btn blue-grey lighten-5"  href="/login">
            <span class="blue-grey-text text-darken-4">
              Login
            </span>
          </a>
        </li>
      </ul>
    </div>
</nav>

<!--
<div class="center">
  <div class="container">
      <div class="col s12 m6">
        <div class="card">
          <div class="card-content white-text">
            <span class="card-title  teal-text text-darken-4 center"><b>Register</b></span>
            <p>
              <div class="row">
                <form method='POST' class="col s12 black-text" action='' enctype='multipart/form-data'>{% csrf_token %}
                {{ form}}
                    <input type='submit' class='btn waves-effect waves-light' value='{{title}}' />
                </form>

              </div>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div> -->

  <div class="row" style = "padding-top:20px">
    <div class="col s6 offset-s3">

      <div class="card z-depth-3 grey lighten-4">
        <form method='POST' action='' enctype='multipart/form-data'>
          {% csrf_token %}

        <div class="card-content" style="padding-bottom:0px">
          <span class="card-title center" style="padding-top:0px ;margin-top:0px"><h4 style="margin-top:0px">Register</h4></span>
          <div class="row">
            <div class="input-field col s12">
              <input id="username" name="username" type="text" class="validate" required="">
              <label for="username">Username</label>
            </div>
            <div class="input-field col s12">
              <input id="email" name="email" type="email" class="validate" required="">
              <label for="email">Email</label>
            </div>
            <div class="input-field col s12">
              <input id="email2" name="email2" type="email" class="validate" required="">
              <label for="email2">Confirm Email</label>
            </div>
            <div class="input-field col s12">
              <input id="password" name="password" type="password" class="validate" required="">
              <label for="password">Password</label>
            </div>
          </div>
        </div>
        <div class="card-action" style="padding:0px;margin:5px">
        <div class="row">
          <div class="input-field center" style="margin:20px">
            <input type="submit" value="SignUp" class="btn waves-effect">
          </div>
        </div>
        </div>
      </form>
      </div>
    </div>
  </div>


  <!--Import jQuery before materialize.js-->
  <script type="text/javascript" src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'materialize/js/materialize.min.js' %}"></script>
  <script type="text/javascript">

  </script>
</body>
</html>

mysite/templates/neoyoutube/search.html
{% extends "neoyoutube/index.html" %}
{% block content %}
<div class="row grey lighten-3" style="margin:0px">
  <div class="container" style="padding-top: 50px; padding-bottom: 50px">
    <ul class="pagination center" style="margin:0px">
      {% for i in page_range %}
      {% if i == page %}
      <li class="active teal"><a href="?search={{query}}&page={{page}}">{{ i }}</a></li>
      {% else %}
      <li class="waves-effect"><a href="?search={{query}}&page={{ i }}">{{ i }}</a></li>
      {% endif%}

      {% endfor%}
    </ul>
  {% for data in video_data  %}
  <a href = "/watch?id={{data.videoInfo.id}}">
    <div class="card horizontal z-depth-5 grey-text text-darken-1 hoverable">
      <div class="card-image">
        <img src="{{ data.videoInfo.snippet.thumbnails.default.url  }}" height="150" style="padding:10px;">
      </div>
      <div class="card-stacked">
        <div class="card-content" style="padding:8px">
          <b>
              {{ data.videoInfo.snippet.localized.title }}
          </b>
          <p>

            <span style = "font-size:14px"><b>{{ data.videoInfo.snippet.channelTitle}}</b></span>
          </p>
          <p>
            <span><i class="material-icons dp48">visibility</i><b><sup style = "font-size:14px"> {{data.videoInfo.statistics.viewCount }} </sup></b></span>
          </p>
          <p>{{ data.videoInfo.snippet.localized.description }}</p>
        </div>
      </div>
    </div>
  </a>

  {% endfor %}
</div>
<ul class="pagination center">
  {% for i in page_range %}
  {% if i == page %}
    <li class="active teal"><a href="?search={{query}}&page={{page}}">{{ i }}</a></li>
  {% else %}
    <li class="waves-effect"><a href="?search={{query}}&page={{ i }}">{{ i }}</a></li>
  {% endif%}

  {% endfor%}
</ul>
</div>
<!--
<script type="text/javascript">
  document.onload = function() {
    document.getElementsById('search').Value = '{{ query }}';
  }
</script> -->
{% endblock content %}

mysite/templates/neoyoutube/show.html
{% extends "neoyoutube/index.html" %}
{% block content %}
<ul class="pagination center">
  {% for i in page_range %}
  {% if i == page %}
  <li class="active teal"><a href="?page={{page}}">{{ i }}</a></li>
  {% else %}
  <li class="waves-effect"><a href="?page={{ i }}">{{ i }}</a></li>
  {% endif%}

  {% endfor%}
</ul>

<div class="row">
 {% for data in show_videos %}
 <div class="col s3">
   <a href="watch/?id={{data.videoInfo.id}}" class="black-text">
     <div class="card z-depth-2 grey lighten-4">
       <div class="card-image" style = "padding-left: 10px; padding-right: 10px; padding-top: 10px">
         <img src="{{ data.videoInfo.snippet.thumbnails.medium.url  }}" width="295.250" height="166.078">
       </div>
       <div class="card-content">
         <p  class="truncate"><b>{{ data.videoInfo.snippet.localized.title }}</b></p>
            <span style = "font-size:14px"> {{ data.videoInfo.snippet.channelTitle}}</span>
            <span style = "position: absolute; right: 20px; bottom: 0px;"><i class="material-icons dp48">visibility</i><b><sup style = "font-size:14px">{{data.videoInfo.statistics.viewCount }}</sup></b></span>
        </div>
      </div>
    </a>
  </div>
{% endfor %}
 </div>
 <ul class="pagination center">
   {% for i in page_range %}
   {% if i == page %}
   <li class="active teal"><a href="?page={{page}}">{{ i }}</a></li>
   {% else %}
   <li class="waves-effect"><a href="?page={{ i }}">{{ i }}</a></li>
   {% endif%}

   {% endfor%}
 </ul>
{% endblock content %}

mysite/templates/neoyoutube/watch.html
{% extends "neoyoutube/index.html" %}
{% block content %}
  <div class="row grey lighten-3" style="padding-top: 50px; padding-bottom: 50px">
  <div class="row">
    <div class="col s8">
      <div class="card-content">
        <iframe width="854" height="480" src="https://www.youtube.com/embed/{{ id }}" frameborder="0" allowfullscreen></iframe>
      </div>
      <div class="card">
        <div class="card-content">
              <span class="card-title">{{ data.videoInfo.snippet.title }}</span>
              <div class="row grey-text text-darken-1">
                <div class="left">
                  <p>
                    <b><u>
                      <a href="/channel?channelid={{data.videoInfo.snippet.channelId}}" class="black-text tooltipped" data-position="right" data-delay="30" data-tooltip="Visit Channel">
                        {{ data.videoInfo.snippet.channelTitle }}
                      </a>
                    </u></b>
                  </p>
                </div>
                <div class="right">
                  <p>
                    {{data.videoInfo.statistics.viewCount}} views

                  </p>
                </div>
              </div>
                <div class="row">
                  <div style="padding-left: 0px; padding-top:0px; bottom:5px">
                    <ul class="collapsible z-depth-0" data-collapsible="accordion">
                      <li>
                        <div class="collapsible-header ">
                          <p>
                        <div class="center">
                          Show Description
                        </div>
                        </p>
                        </div>
                        <div class="collapsible-body">
                          <span>{{ data.videoInfo.snippet.description}}</span>
                        </div>
                      </li>
                    </ul>
                  </div>

                </div>
        </div>
      </div>
    </div>
    <div class="col s4 white" style="overflow-y: scroll; height:1000px;">
      {% for vi in recommends%}
      <a href = "/watch?id={{vi.videoInfo.id}}">
        <div class="card horizontal hoverable grey-text text-darken-2">
          <div class="card-image">
            <img src="{{ vi.videoInfo.snippet.thumbnails.medium.url  }}" height="150" style="padding:10px;">
          </div>
          <div class="card-stacked">
            <div class="card-content" style="padding:0px; padding-top:5px">
              <p>
                <b>{{ vi.videoInfo.snippet.localized.title }}</b>
              </p>
              <p>
                <span style = "font-size:10px">{{ vi.videoInfo.snippet.channelTitle}}</span>
              </p>
              <p>
                <span><i class="material-icons dp48">visibility</i><sup style = "font-size:14px"> {{vi.videoInfo.statistics.viewCount }} </sup></span>
              </p>
              </div>
            </div>
          </div>
        </a>
        {% endfor %}
      </div>
  </div>
</div>
<script type="text/javascript">

$('document').ready(function(){
  $('.collapsible').collapsible();
});
</script>
{% endblock content %}